defaults:
  - _self_
  - model: pointbert   

dataset:
  num_classes: 14   
  npoints: 8192
  batch_size: 8
  data_path: dataset/pretrain_pointbert_8192 #Important
  random_rotation: True

mlflow_experiment_name: Classification_Backbone_Comparrison

mode: test
test_path: ./experiments/bruecke/500_epochs_1024
epochs: 300

hydra:
  run:
    dir: ./experiments/bruecke/500_epochs_1024
  job:
    chdir: True