defaults:
  - _self_
  - model: pointbert   

dataset:
  num_classes: 14   
  npoints: 8192
  batch_size: 8
  data_path: dataset/pretrain_pointbert_8192 #Important
  random_rotation: True

mlflow_experiment_name: Binary_Bridge_Backbone_Comparison_cross_entropy

mode: train
test_path: ./experiments/bruecke/baseline
epochs: 300

hydra:
  run:
    dir: ./experiments/bruecke/340_epochs_random_rotation_1024
  job:
    chdir: True